### ISSUE TITLE
Add link to Github on AMO page

### ISSUE THREAD

**Issue by Gitoffthelawn** [TheRealMarnes/url-manager#1]
Add a link to this repo on AMO page.

**Comment by TheRealMarnes** [comment]
![](http://vgy.me/fUg9nn.png)

**Comment by Gitoffthelawn** [comment]
You may want to enter it in via the AMO interface as well.  Take a look at Auto-Sort Bookmarks to see an example.  You can optionally enter an email address to appear above/below it.

**Comment by TheRealMarnes** [comment]
@Gitoffthelawn my email is already there... http://vgy.me/GvP0h7.png

I might add github as the homepage link, I dunno, I'll see. But it's not like I don't know it's there anyway.

**Comment by Gitoffthelawn** [comment]
Sounds good.
